#set(LEMON_UUID_WIN32RPC TRUE)
set(LEMON_RANDOM_WINCRYPT TRUE)
set(LEMON_USE_WIN32_FTIME TRUE)
set(LEMON_USE_WIN32_FIBER TRUE)
set(LEMON_TEXT_CONVERTER_WIN32 TRUE)
lemon_option(
  LEMON_UUID
  DEFAULT WIN32RPC
  VALUES BUILDIN WIN32RPC
  DESCRIPTION "the uuid implement")